### PR TITLE
Respect :file in msg when evaluating forms

### PR DESCRIPTION
**Pull request by jpmonettas**
This is a possible fix for https://github.com/nrepl/piggieback/issues/126

### CODE REVIEW

**Comment by bbatsov** [comment]
Ops, since I totally didn't see this PR when it was originally submitted. Sorry about that!

**Comment by jpmonettas** [comment]
Hey, np, I also completely forgot about it.
So yeah, I remember this was working, but also made sense. `cljs.repl/evaluate-form` accepts a file, and we are giving it always `<cljs repl>` which I guess means we don't know the file. But for evaluation messages that comes with file info we can provide it instead.

**Comment by bbatsov** [comment]
@alexander-yakushev Does this look good to you?

**Comment by alexander-yakushev** [comment]
Looks fine to me, let's merge it.

**Comment by bbatsov** [comment]
@jpmonettas Can you rebase this and add a changelog entry?

**Comment by alexander-yakushev** [comment]
@bbatsov I took the liberty myself. Let's merge?

**Comment by jpmonettas** [comment]
Just seeing this, thanks @alexander-yakushev and @bbatsov

**Pull request merged**
